"""empty message

Revision ID: 06f93592e36a
Revises: 
Create Date: 2020-10-04 13:49:52.943322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f93592e36a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('nature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('office',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('technician',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('no', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.String(length=100), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('photo_fn', sa.String(length=100), nullable=True),
    sa.Column('office_client_id', sa.String(), nullable=True),
    sa.Column('mode_approach_id', sa.String(), nullable=True),
    sa.Column('nature_type_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mode_approach_id'], ['mode.public_id'], ),
    sa.ForeignKeyConstraint(['nature_type_id'], ['nature.public_id'], ),
    sa.ForeignKeyConstraint(['office_client_id'], ['office.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('repair',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('technician_fixer_id', sa.String(), nullable=True),
    sa.Column('request_task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_task_id'], ['request.public_id'], ),
    sa.ForeignKeyConstraint(['technician_fixer_id'], ['technician.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair')
    op.drop_table('request')
    op.drop_table('technician')
    op.drop_table('office')
    op.drop_table('nature')
    op.drop_table('mode')
    # ### end Alembic commands ###
